name = "system-studio-firefly"
main = "src/index.ts"
compatibility_date = "2024-11-29"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "studio_firefly"
database_id = "f884ec31-cb9b-48e8-852d-cfdcfd51172f"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

[observability.logs]
enabled = true